# Generated by Django 6.1.1 on 2026-09-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.IntegerField(blank=True, default='0', null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('objeto_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, default='0', null=True)),
                ('recibir_cantidad', models.IntegerField(blank=True, default='0', null=True)),
                ('recibir_de', models.CharField(blank=True, max_length=50, null=True)),
                ('usado_cantidad', models.IntegerField(blank=True, default='0', null=True)),
                ('usado_por', models.CharField(blank=True, max_length=50, null=True)),
                ('usado_para', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=50, null=True)),
                ('reorden_nivel', models.IntegerField(blank=True, default='0', null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('exportar_a_CSV', models.BooleanField(default=False)),
            ],
        ),
    ]
